### ISSUE TITLE
Use hosted Cobalt instead of interfacing w/ datasets directly

### ISSUE THREAD

**Issue by qasim** [kshvmdn/what-class-is-this#2]
Do you think the project should make API requests to Cobalt instead of using the datasets? We could calculate the current term based on date and pass that through a filter endpoint along with the other requirements, then return and display the courses + exact sections that the user may be in. I'd love to give it a `$ go` if you think so!

**Comment by kashav** [comment]
I'd originally intended to do something like this, but it kind of reduced/removed the need for any backend at all (everything you mentioned (making/preparing requests) can be done just as easily on the front-end). Since I intended for this to be a Go learning experience (you can probably tell by the semi-complete front-end), I decided to do what I did and essentially rebuild Cobalt.

If you can find a reason to keep/add to the backend while using the Cobalt API, then `$ go` for it! 😉

**Comment by qasim** [comment]
That makes sense to me. Yeah this is Cobalt's newest competitor. 😈
